parameters: {}
environment: {}
packages:
    - name: kube
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: list
          binary: false
          main: ""
          runtime: python:3.11
          web: true
          webSecure: false
          parameters: {}
          environment:
            SPACES_ACCESS_KEY: ${SPACES_ACCESS_KEY}
            SPACES_SECRET_KEY: ${SPACES_SECRET_KEY}
          annotations: {}
          limits:
            memory: 1024
            timeout: 5000
